version: '3.7'
services:
    db:
        container_name: db-mintos
        build: docker/postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        networks:
            - db
        ports:
            - 15432:5432
    php:
        container_name: php-fpm-mintos
        build: docker/php8-fpm
        ports:
            - 9001:9001
        volumes:
            - .:/var/www/symfony
        depends_on:
            - db
        networks:
            - db
            - php
    nginx:
        container_name: nginx-mintos
        build: docker/nginx
        ports:
            - 80:80
        depends_on: 
            - php
            - db
        networks:
            - php
            - db
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./public:/var/www/symfony/public
networks:
    db:
    php: